language: c

sudo: false

env:

cache:

addons:
    apt:
        packages:
            - make
            - unzip
            - gcc
            - wget

script:
    # Get FreeRTOS source
    - make -f Makefile.tools
    # Compile all example
    - make -f Makefile.examples
