
#ifndef FREERTOS_LINUX_DEVL_EXAMPLES_FREERTOS_LWIP_PPP_SIO_GSM_H_
#define FREERTOS_LINUX_DEVL_EXAMPLES_FREERTOS_LWIP_PPP_SIO_GSM_H_

struct sio_status_s {
	int fd;
};

#endif /* FREERTOS_LINUX_DEVL_EXAMPLES_FREERTOS_LWIP_PPP_SIO_GSM_H_ */
